apiVersion: apps/v1
kind: Deployment
metadata:
  name: messaging-blue
spec:
  replicas: 2
  selector:
    matchLabels:
      app: messaging
      version: blue
  template:
    metadata:
      labels:
        app: messaging
        version: blue
    spec:
      containers:
        - name: messaging
          image: wisdom62/messaging-app:1.0
          ports:
            - containerPort: 8000
          env:
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: messaging-app-secret
                  key: SECRET_KEY
            - name: DEBUG
              valueFrom:
                secretKeyRef:
                  name: messaging-app-secret
                  key: DEBUG
            - name: MySQL_DB
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_DB
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_USER
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_PASSWORD

---
apiVersion: v1
kind: Service
metadata:
  name: messaging-blue
spec:
  type: NodePort
  selector:
    app: messaging
    version: blue
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30000
