#!usr/bin/env bash
set -e

echo "Deploying blue version..."
kubectl apply -f blue_deployment.yaml
kubectl apply -f kubeservice.yaml

echo "Deploying green version..."
kubectl apply -f green_deployment.yaml

echo "Checking logs for green version..."
GREEN_POD=$(kubectl get pods -l app=messaging,version=green -o jsonpath="{.items[0].metadata.name}")
kubectl logs $GREEN_POD

read -p "If logs look good, press Enter to switch traffic to green..."

echo "Switching service to green..."
kubectl patch service messaging-service -p '{"spec":{"selector":{"app":"messaging","version":"green"}}}'

echo "Traffic switched to green version."
