name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: rOOtX_fash$
          MYSQL_DATABASE: messaging_app_db
          MYSQL_USER: messaging_app_user
          MYSQL_PASSWORD: rOOtX_fash$
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h 127.0.0.1 -u root -proot"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    env:
      DB_HOST: 127.0.0.1
      DB_PORT: 3306
      DB_NAME: messaging_app_db
      DB_USER: messaging_app_user
      DB_PASSWORD: rOOtX_fash$
      DJANGO_SETTINGS_MODULE: messaging_app.settings

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python3 -m pip3 install --upgrade pip3
          pip3 install -r messaging_app/requirements.txt
          pip3 install flake8 coverage

      - name: Run flake8 (linting)
        run: |
          echo "Running flake8..."
          flake8 messaging_app --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 messaging_app --count --exit-zero --max-complexity=10 --max-line-length=88 --statistics


      - name: Wait for MySQL
        run: |
          until mysqladmin ping -h"$DB_HOST" -u"$DB_USER" -p"$DB_PASSWORD" --silent; do
            echo "Waiting for MySQL..."
            sleep 5
          done

      - name: Run migrations
        run: |
          python3 manage.py migrate --noinput

      - name: Run tests
        run: |
          python3 manage.py test
