version: '3.9'

services:
  db:
    image: mysql:8.0
    container_name: messaging_app_db
    restart: always
    env_file:
      - .env
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    
  web:
    build: .
    container_name: messaging_app_web
    restart: always
    command: >
      sh -c "
      until mysqladmin ping -h db --silent; do
        echo 'Waiting for MySQL...';
        sleep 2;
      done &&
      python3 manage.py migrate &&
      python3 manage.py runserver 0.0.0.0:8000
      "
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      SECRET_KEY: $(SECRET_KEY)
      DEBUG: $(DEBUG)
      ALLOWED_HOST: $(ALLOWED_HOST)
      MYSQL_DATABASE: $(MYSQL_DATABASE)
      MYSQL_USER: $(MYSQL_USER)
      MYSQL_PASSWORD: $(MYSQL_PASSWORD)
      MYSQL_HOST: $(MYSQL_HOST)
      MYSQL_PORT: 3306
      MYSQL_ROOT_PASSWORD: $(MYSQL_ROOT_PASSWORD)
    depends_on:
      - db
    
volumes:
  db_data: