#!/usr/bin/env bash


if ! command -v minikube &> /dev/null
then
	echo "Minikube could not be found. Please install Minikube first."
	exit 1
fi

echo "Minikube is installed. Proceeding..."

echo "Starting Minikube cluster..."
minikube start --driver=docker

echo "Checking cluster info..."
kubectl cluster-info

echo "Retreiving available pods..."
kubectl get pods --all-namespaces

echo "Kubernetes setup complete!"
